### ISSUE TITLE
Use `colorama` for colours instead of raw ANSII characters

### ISSUE THREAD

**Issue by Chiroyce1** [Chiroyce1/scratch-user-data#2]
I'll work on this locally and make a new branch

**Comment by Chiroyce1** [comment]
Added the [beta branch](https://github.com/Chiroyce1/scratch-user-data/tree/beta) - and updated it with new dependencies, haven't started changing the code _yet_.

**Comment by Chiroyce1** [comment]
[Latest commit](https://github.com/Chiroyce1/scratch-user-data/commit/c7345ba3468557684f86dd7321a30fb08e7b5093) to `beta` changed all foreground ANSII colours with colorama.

**Comment by imdevarsh** [comment]
You should make colorama only for windows, I think you can still use ANSI codes cross-platform, colorama only fixes for windows

**Comment by Chiroyce1** [comment]
I think it's better to keep the installs same for all platforms...
