### ISSUE TITLE
README.md still mentions scratch-user-data

### ISSUE THREAD

**Issue by mybearworld** [Chiroyce1/scratch-user-data#8]
![The folder name "scratch-user-data" is still used despite the rebrand to scratch-user-info.](https://user-images.githubusercontent.com/130385691/236285403-32a51cdf-a695-41e5-86f8-603b1cacc4e8.png)

**Comment by Chiroyce1** [comment]
Thank you for reporting this issue, resolved in https://github.com/Chiroyce1/scratch-user-info/commit/089acdf42a18cd25a964764693af9d75d6e54d07.
